Zadaca 1
Peglaa/android-vjestina-tmdb pull request #1
Opened 2022-10-24 17:02 UTC by Peglaa

Compose komponente za 1. zadaću.

2022-10-31 15:45 UTC, lauraabramovicfive requested changes

2022-10-31 15:45 UTC, lauraabramovicfive commented on app/src/main/java/agency/five/codebase/android/movieapp/model/Movie.kt
> +    var isFavorite: Boolean,
Revert this. All domain models should only have values stored in them and not variables.

2022-10-31 15:45 UTC, lauraabramovicfive commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/component/ActorCard.kt
> +            .width(145.dp),
Composable components should be as generic as possible, so they can be reused whenever needed. For this reason the size should not be defined here. Instead it should be passed in the function using a modifier

2022-10-31 15:45 UTC, lauraabramovicfive commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/component/ActorCard.kt
> +                modifier = modifier
Modifiers which are passed in are designed so that they should be used by a single layout node in the composable function. Do not reuse modifiers because it will lead to undesired behaviour (such as padding being applied multiple times). Instead use a new `Modifier` here and anywhere else where there are reused modifiers.

2022-10-31 15:45 UTC, lauraabramovicfive commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/component/ActorCard.kt
> +                modifier = modifier
Use a new `Modifier` here.

2022-10-31 15:45 UTC, lauraabramovicfive commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/component/ActorCard.kt
> +                    .width(100.dp),
You shouldn't add a fixed `width` or `height` on a text, because it can work unexpectedly for different font sizes and screen sizes. It should be displayed in the the whole area between the paddings. Remove this property from here and anywhere else where text has a fixed size. If you don't want your text to go all the way to the end, add padding at the end to prevent this.

2022-10-31 15:45 UTC, lauraabramovicfive commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/component/ActorCard.kt
> +                modifier = modifier
Use new `Modifier` here.

2022-10-31 15:45 UTC, lauraabramovicfive commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/component/ActorCard.kt
> +}
All files should have an empty line at the end. You can configure Android studio to set it automatically by checking
`Preferences -> Editor -> General -> Ensure line feed at file end on Save.`

2022-10-31 15:45 UTC, lauraabramovicfive commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/component/CrewItem.kt
> +){
This file is not properly formatted. You can format a file by using `Ctrl + Alt + L` on Windows, or `Command + Option + L` on Mac. Use this for all files.

2022-10-31 15:45 UTC, lauraabramovicfive commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/component/CrewItem.kt
> +    crewItemViewState: CrewItemViewState,
All composable functions should have a `modifier` parameter.

2022-10-31 15:45 UTC, lauraabramovicfive commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/component/CrewItem.kt
> +    Column() {
Add passed modifier to `Column`.

2022-10-31 15:45 UTC, lauraabramovicfive commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/component/FavoriteButton.kt
> +    contentDescription: String = "Favorite button"
Don't hardcode strings anywhere other than the preview functions. Instead put it in the `strings.xml` file and extract it using `stringResource(R.string.string_id)`

2022-10-31 15:45 UTC, lauraabramovicfive commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/component/FavoriteButton.kt
> +    val fav = remember { mutableStateOf(false) }
Instead of creating `fav` variable here which holds the changed value, you should pass an `isFavorite` parameter and an onClick function in composable, and use it instead of `fav`. This is to keep composable stateless. You can find more info about it in [State Hoisting](https://developer.android.com/jetpack/compose/state#state-hoisting)

2022-10-31 15:45 UTC, lauraabramovicfive commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/component/FavoriteButton.kt
> +            .width(28.dp)
No need for setting the `width` two times.

2022-10-31 15:45 UTC, lauraabramovicfive commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/component/MovieCard.kt
> +            .height(180.dp)
Don't use fixed size here. Pass it with a `modifier` when using `MovieCard`.

2022-10-31 15:45 UTC, lauraabramovicfive commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/component/MovieCard.kt
> +            .clickable {  },
Pass an onClick to `MovieCard` and call it here. No need for having an empty `clickable`.

2022-10-31 15:45 UTC, lauraabramovicfive commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/component/MovieCategoryLabel.kt
> +    movieCategoryLabelViewState: MovieCategoryLabelViewState
All composable functions should have a modifier parameter.

2022-10-31 15:45 UTC, lauraabramovicfive commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/component/MovieCategoryLabel.kt
> +            modifier = modifier.fillMaxWidth()
Use a new `Modifier` here.

2022-10-31 15:45 UTC, lauraabramovicfive commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/component/MovieCategoryLabel.kt
> +    movieCategoryLabelViewState: MovieCategoryLabelViewState
Pass a modifier here.

2022-10-31 15:45 UTC, lauraabramovicfive commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/component/UserScoreProgressBar.kt
> +            text = (score * 10f).toString(), //THIS BREAKS WHEN USING DOUBLE FOR SCORE(e.g. 0.01, 0.05 etc)
You can use something like `"%.1f".format(score * 10f)` here to keep it form breaking. Extract it at the top of the file like `private const val SCORE_FORMAT = "%.1f"` and use that in the code instead of using it directly here.

2022-10-31 15:45 UTC, lauraabramovicfive commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/component/UserScoreProgressBar.kt
> +        Canvas(modifier = modifier
Use new `Modifier` here.

2022-10-31 15:45 UTC, lauraabramovicfive commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/component/UserScoreProgressBar.kt
> +    )
Animation is very nice

2022-10-31 15:45 UTC, lauraabramovicfive commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/component/MovieCard.kt
> +    movie: Movie
Do not pass domain model `Movie` directly into composable function. Instead create and pass a data class, something like `MovieViewState`, as you did with `ActorCard` and `CrewItem` composables.

2022-11-01 17:59 UTC, Peglaa commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/component/UserScoreProgressBar.kt
> +    )
Thank you!

2022-11-08 14:25 UTC, lauraabramovicfive requested changes

2022-11-08 14:25 UTC, lauraabramovicfive commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/component/MovieCard.kt
> +                onClick = {})
Pass an `onFavoriteButtonClicked` parameter to `MovieCard` and pass it here.

2022-11-11 12:28 UTC, lauraabramovicfive requested changes

2022-11-11 12:28 UTC, lauraabramovicfive commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/component/MovieCard.kt
> +                isFavorite = true,
Don't hardcode `isFavorite` value here. Instead `MovieCardViewState` should have an `isFavorite` field which will be read here.

2022-11-11 13:10 UTC, lauraabramovicfive approved these changes

2022-11-11 13:17 UTC, merged