Zadaca 2
Peglaa/android-vjestina-tmdb pull request #2
Opened 2022-11-18 19:25 UTC by Peglaa

There is a bug in this MR. When clicking on a category label on Home screen, the recomposition will not trigger and the selection will only be visible when you navigate to some other screen and then back to the Home screen.

2022-11-22 12:58 UTC, matejsalkovic requested changes

2022-11-22 12:58 UTC, matejsalkovic commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/moviedetails/MovieDetailsScreen.kt
> +            }
Click should be handled somewhere. In next homework it will be passed to ViewModel, but as it will be passed from `MovieDetailsRoute`, for now you should have empty implementation there.

2022-11-22 12:58 UTC, matejsalkovic commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/moviedetails/MovieDetailsScreen.kt
> +fun ImageHeader(
Make private all functions that don't need to be public.

2022-11-22 12:58 UTC, matejsalkovic commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/home/HomeScreen.kt
> +                else -> throw IllegalStateException()
Try to rewrite this again. Instead of using constant integers, you could use enum `ordinal` field. Also, you can create private function that would look something like this,
```kotlin
private fun mapToViewState(categoryList: LIst<MovieCategory>, categoryId: Int): HomeMovieCategoryViewState
```
Then you can write when with same behavior for multiple categories, i.e. something like this
```kotlin
when (categoryId) {
    MovieCategory.POPULAR_STREAMING.ordinal,
    MovieCategory.POPULAR_FOR_RENT.ordinal,
    MovieCategory.POPULAR_ON_TV.ordinal,
    MovieCategory.POPULAR_IN_THEATRES.ordinal,
    -> {
        popularMovies = mapToViewState(popularMovieCategories, categoryId)
    }
    /* ... */
    }
}
```
Then you also don't need to pass category list in `onMovieCategoryClicked` function.

2022-11-22 12:58 UTC, matejsalkovic commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/favorites/FavoritesScreen.kt
> +                    onFavoriteButtonClicked = { onFavoriteButtonClick() }
No need for creating a new lambda, you can simply pass the one you already have.

2022-11-22 12:58 UTC, matejsalkovic commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/favorites/FavoritesScreen.kt
> +                key = { movie -> movie.id }) { card ->
`)` in new line.

2022-11-24 20:22 UTC, Peglaa commented on app/src/main/java/agency/five/codebase/android/movieapp/navigation/NavigationItem.kt
> +    }
Done.

2022-11-24 20:23 UTC, Peglaa commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/component/FavoriteButton.kt
> +fun onImageClick() {
Removed.

2022-11-24 20:23 UTC, Peglaa commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/component/MovieCategoryLabel.kt
> +    when (movieCategoryLabelViewState.isSelected) {
Reverted.

2022-11-24 20:26 UTC, Peglaa commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/favorites/mapper/FavoritesMapperImpl.kt
> +        )
Fixed.

2022-11-24 20:30 UTC, Peglaa commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/home/mapper/HomeScreenMapperImpl.kt
> +        val homeMovieViewStates = mutableListOf<HomeMovieViewState>()
Fixed.

2022-11-24 20:30 UTC, Peglaa commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/moviedetails/mapper/MovieDetailsMapper.kt
> +}
Thought I configured AS to do this automatically... Fixed.

2022-11-24 20:31 UTC, Peglaa commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/moviedetails/mapper/MovieDetailsMapperImpl.kt
> +        val castList = mutableListOf<ActorCardViewState>()
Fixed.

2022-11-24 20:40 UTC, Peglaa commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/main/MainScreen.kt
> +fun RowScope.AddItem(
Fixed.

2022-11-24 20:41 UTC, Peglaa commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/main/MainScreen.kt
> +        enabled = currentDestination?.route != destination.route,
Removed.

2022-11-24 20:44 UTC, Peglaa commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/moviedetails/MovieDetailsScreen.kt
> +                CrewItem(
Fixed.

2022-11-24 20:51 UTC, Peglaa commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/moviedetails/MovieDetailsScreen.kt
> +fun ImageHeader(
Fixed for entire project.

2022-11-24 20:51 UTC, Peglaa commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/home/HomeScreen.kt
> +fun HomeScreenPreview() {
Fixed.

2022-11-24 20:53 UTC, Peglaa commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/home/HomeScreen.kt
> +    var upcomingCategoryViewState by remember { mutableStateOf(upcomingCategoryViewState) }
Done.

2022-11-24 20:54 UTC, Peglaa commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/favorites/FavoritesScreen.kt
> +                    onFavoriteButtonClicked = { onFavoriteButtonClick() }
Fixed.

2022-11-24 20:54 UTC, Peglaa commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/favorites/FavoritesScreen.kt
> +                key = { movie -> movie.id }) { card ->
Fixed.

2022-11-24 21:08 UTC, Peglaa commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/home/HomeScreen.kt
> +                else -> throw IllegalStateException()
Rewritten. Thanks!

2022-11-24 21:10 UTC, Peglaa commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/moviedetails/MovieDetailsScreen.kt
> +            }
Fixed.

2022-11-24 21:10 UTC, Peglaa commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/main/MainScreen.kt
> +    Image(
Fixed.

2022-11-24 21:32 UTC, Peglaa commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/main/MainScreen.kt
> +    Image(
Btw, I replaced the arrow from the design with Icons.Default.ArrowBack, I'm not sure if this is ok or if I should make the arrow from the design somehow work with Icon?

2022-11-24 21:34 UTC, Peglaa commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/main/MainScreen.kt
> +                        onFavoriteButtonClicked = {} // your code goes here ...
Fixed, leaving it empty for now I suppose.

2022-11-24 21:34 UTC, Peglaa commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/main/MainScreen.kt
> +                    })
Fixed.

2022-11-24 21:35 UTC, Peglaa commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/main/MainScreen.kt
> +    var showBottomBar by remember { mutableStateOf(true) }
Fixed, hopefully the right way, if I understood derivedStateOf correctly. Works great when testing the app so...

2022-11-24 21:41 UTC, Peglaa commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/moviedetails/MovieDetailsScreen.kt
> +    )
Fixed. The way I was doing it previously wouldn't allow me to put it in the MainScreen. Now that I'm using method reference for navigateUp() and derivedStateOf it started working.

2022-11-24 21:42 UTC, Peglaa commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/moviedetails/MovieDetailsScreen.kt
> +        * IS THIS A HACKFIX? (SEEMS LIKE IT IS AND THERE IS A CLEANER SOLUTION)*/
I will leave it like it is for now if that is ok.

2022-11-26 08:21 UTC, matejsalkovic requested changes

2022-11-26 08:21 UTC, matejsalkovic commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/main/MainScreen.kt
> +        }
Here you can use `navBackStackEntry?.destination?.route` for comparison instead of finding destinations.

2022-11-26 10:34 UTC, Peglaa commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/main/MainScreen.kt
> +        }
Fixed.

2022-11-28 11:32 UTC, merged